# Task3: CREDIT CARD FRAUD DETECTION WITH PYTHON
####  By TARANJEET KAUR
####  FEB Batch, Domain: Data Science
####  Objective: To Build a machine learning model to identify fraudulent credit card transactions.

# Importing Necessary Libraries

In [36]:
import numpy as np
import pandas as pd

# Loading the dataset

In [2]:
df = pd.read_csv("C:/Users/Taranjeet Kaur/Downloads/creditcard.csv/creditcard.csv", encoding='ISO-8859-1')

In [3]:
df.head(7)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
6,4.0,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,...,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0

## Data filtering and preprocessing

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [5]:
df.shape

(284807, 31)

In [6]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [7]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [8]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

## Distribution of real and fraud transactions

In [9]:
real = df[df.Class == 0]
fraud = df[df.Class == 1]

In [10]:
print(real.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [11]:
real.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [12]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

## Under Sampling

In [13]:
real_sample = real.sample(n=492)

In [14]:
new_df = pd.concat([real_sample, fraud], axis=0)

In [15]:
new_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
95292,65242.0,-0.631701,1.049422,1.452194,2.576940,0.534141,-0.231687,0.583737,-0.103133,-1.418305,...,0.191249,0.602310,0.204187,0.418955,-0.307745,0.082757,-0.193404,0.147585,0.00,0
28155,34879.0,-2.107661,1.089782,1.580844,1.128106,-0.209787,3.291074,-1.739580,-1.238199,-0.408145,...,-1.251701,0.809315,-0.022795,-1.329709,-0.098954,-0.137197,0.263690,-0.005541,71.45,0
141801,84496.0,1.304953,-0.443103,0.541756,-0.910183,-0.895507,-0.376930,-0.657119,0.075359,2.030216,...,-0.078824,-0.020759,-0.127974,-0.471585,0.577939,-0.630614,0.086117,0.024520,1.00,0
149529,91416.0,1.963936,-0.161621,-0.939007,0.529377,-0.109439,-0.951444,0.110689,-0.487212,2.156715,...,-0.022441,0.501608,-0.013614,0.099040,0.219713,0.142464,-0.049741,-0.056991,50.00,0
166555,118157.0,-0.173895,0.834185,2.651017,4.514929,0.136188,0.973530,-0.203066,0.133586,-1.132918,...,0.061944,0.386792,-0.017408,-0.142453,-0.870675,0.228859,0.070045,-0.023116,10.61,0

In [24]:
new_df['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

## Splitting the data into features and targets

In [25]:
x = new_df.drop(columns='Class', axis = 1)
y = new_df['Class']

In [26]:
print(x)

            Time        V1        V2        V3        V4        V5        V6  \
95292    65242.0 -0.631701  1.049422  1.452194  2.576940  0.534141 -0.231687
28155    34879.0 -2.107661  1.089782  1.580844  1.128106 -0.209787  3.291074
141801   84496.0  1.304953 -0.443103  0.541756 -0.910183 -0.895507 -0.376930
149529   91416.0  1.963936 -0.161621 -0.939007  0.529377 -0.109439 -0.951444
166555  118157.0 -0.173895  0.834185  2.651017  4.514929  0.136188  0.973530
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
95292   0.583737 -0.103133 -1.418305  ... -0.029957  0.191249  0.602310
28155  -1.739580 -1.238199 -0.408145  ...  0.519613 -1.251701  0.809315
141801 -0.657119  0.075359  2.030216  ... -0.163111 -0.078824 -0.020759
149529  0.110689 -0.487212  2.156715  ... -0.084603 -0.022441  0.501608
166555 -0.203066  0.133586 -1.132918  ...  0.320064  0.061944  0.386792
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
95292   0.204187  0.418955 -0.307745  0.082757 -0.193404  0.147585    0.00
28155  -0.022795 -1.329709 -0.098954 -0.137197  0.263690 -0.005541   71.45
141801 -0.127974 -0.471585  0.577939 -0.630614  0.086117  0.024520    1.00
149529 -0.013614  0.099040  0.219713  0.142464 -0.049741 -0.056991   50.00
166555 -0.017408 -0.142453 -0.870675  0.228859  0.070045 -0.023116   10.61
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [27]:
print(y)

95292     0
28155     0
141801    0
149529    0
166555    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

## Splitting the data into training data and test data

In [29]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, stratify=y, random_state = 2)

In [30]:
lr = LogisticRegression()
lr.fit(x_train, y_train)

LogisticRegression()

## Accuracy Score

In [32]:
x_train_prediction = lr.predict(x_train)
train_data_accuracy = accuracy_score(x_train_prediction, y_train)

In [33]:
print(train_data_accuracy)

0.9415501905972046

In [34]:
x_test_prediction = lr.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [35]:
print(test_data_accuracy)

0.9187817258883249